services:
  dsr:
    build:
      context: .
      target: app
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    environment:
      DSR_MODE: ${DSR_MODE:-gui}
      DESKTOP_RES: ${DESKTOP_RES:-800x600}
      DISPLAY: ${DISPLAY:-}
    group_add:
      - render
      - video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash

  dsr-igpu:
    extends:
      service: dsr
    build:
      context: .
      target: igpu
    image: dsr:igpu
    devices:
      - /dev/dri/

  dsr-nvidia:
    extends:
      service: dsr
    build:
      context: .
      target: nvidia
    image: dsr:nvidia
    runtime: nvidia
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
